### ISSUE TITLE
R Implementation?

### ISSUE THREAD

**Issue by dpcook** [pkathail/magic#10]
Any chance of an R implementation in the future? Could work nicely with other R-based processing pipelines for scRNA-Seq data (eg. scater, monocle)

**Comment by dvdijk** [comment]
Yeah, we may do this in the next months.

**Comment by dpcook** [comment]
Update: There appears to be an implementation prepped in the scater package repo, but they're holding off release for a bit it seems

**Comment by dvdijk** [comment]
very interesting! I looked it up and it seems that they didn't implement the adaptive kernel, but instead use the standard kernel that comes with the Destiny diffusion map package. The adaptive kernel is quite crucial for MAGIC to work well so I hope they'll implement that as well.

**Comment by asmagen** [comment]
Hello,
Any news regarding the official or alternative implementation?
Thanks,
Assaf

**Comment by dvdijk** [comment]
Hi Assaf,
We're working on a R implementation. It will be online soon.

**Comment by pkathail** [comment]
We've added an R version of MAGIC! Instructions for installation and usage are in the README,

**Comment by dpcook** [comment]
This is awesome! I'll give it a shot and let you guys know if there are any hurdles
