### ISSUE TITLE
tutorial link not working

### ISSUE THREAD

**Issue by radio1988** [pkathail/magic#14]
It sees that the tutorial link is saying 404 not found:
http://nbviewer.jupyter.org/github/pkathail/magic/blob/magic_develop/notebooks/Magic_single_cell_RNAseq.ipynb

**Comment by pkathail** [comment]
I think it should be fixed now, the correct link is http://nbviewer.jupyter.org/github/pkathail/magic/blob/develop/notebooks/Magic_single_cell_RNAseq.ipynb
