### ISSUE TITLE
log-transform data

### ISSUE THREAD

**Issue by yanwu2014** [pkathail/magic#15]
Is the input data supposed to be log-transformed? It doesn't seem to be in the examples

**Comment by dvdijk** [comment]
It doesn't have to be, but it can.
Either: raw count matrix -> library size normalize -> MAGIC
or: raw count matrix -> library size normalize -> log transform (don't forget pseudo count) -> MAGIC

**Comment by yanwu2014** [comment]
Thanks! Btw there seems to be a bug in the current log_transform function (should it be referencing self.data instead of scdata.data?)

Also this method is awesome! It runs super fast and seems to work well on our datasets so far!
