### ISSUE TITLE
error on import magic: No module named 'Phenograph'

### ISSUE THREAD

**Issue by mfrancesconi81** [pkathail/magic#16]
Hi, 
I installed magic on a Mac Book pro (master branch). Installation was successful but I got an error when I import magic:  ImportError: No module named 'phenograph'

It seems that it didn't install some dependencies

Thanks for your help, 

M.

**Comment by mfrancesconi81** [comment]
I just manually installed the phenograph module it is now working

**Comment by dvdijk** [comment]
ok, great. however we'll fix this since MAGIC doesn't require phenograph
