### ISSUE TITLE
save out to txt

### ISSUE THREAD

**Issue by JoJoBe2017** [pkathail/magic#22]
Hello,

How do I save out the magic massaged results (cell by gene matrix) into txt file so that I can import to R?

Thank you.

**Comment by dpcook** [comment]
Hey there,

After you go through their workflow, you can export to CSV using the to_csv function from Pandas with the following:

```
mat = scdata.magic.data
mat.to_csv(path_or_buf="~/Data/etc/lmagic.matrix.csv")
```

**Comment by JoJoBe2017** [comment]
yes, I figured out.  Thanks.
