### ISSUE TITLE
unable to import gene expression matrix in csv format

### ISSUE THREAD

**Issue by yuqiyuqitan** [pkathail/magic#24]
Hi, i have scRNAseq gene expression matrix in csv format (with rows as genes, columns as cells), but i couldn't perform data statistics or any analysis in MAGIC python GUI. The error i got is shown as the following: 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/magic/mg.py:465: RuntimeWarning: divide by zero encountered in log10
  rowsum = np.log10(self.data.sum(axis=1))
-inf
7.51657024826
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)

**Comment by pkathail** [comment]
Hi, did it output another line after the Traceback saying what kind of error was thrown?
Also, just to make sure I'm understanding correctly, the GUI launched and you got this error when trying to load the data statistics for filtering, correct?
