### ISSUE TITLE
mmread dependency issue

### ISSUE THREAD

**Issue by asmagen** [pkathail/magic#25]
Hello,
Which mmread is the Matlab code trying to use and how can I get it?
Thanks

**Comment by dvdijk** [comment]
hi,
I added mmread.m to Develop

**Comment by asmagen** [comment]
Thanks.
Now I get this error:
Missing symbol '_malloc' required by
'/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices->/System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC->/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata->/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices->/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation->/Applications/MATLAB_R2017a.app/bin/maci64/libmwnativestrings.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwsettingscore.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwservices.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmex.dylib->/Users/magen/projects/magic/matlab/DiffusionGeometry/NearestNeighbors/nn_prepare.mexmaci64'
Missing symbol '_memcpy' required by
'/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices->/System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC->/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata->/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices->/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation->/Applications/MATLAB_R2017a.app/bin/maci64/libmwnativestrings.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwsettingscore.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmwservices.dylib->/Applications/MATLAB_R2017a.app/bin/maci64/libmex.dylib->/Users/magen/projects/magic/matlab/DiffusionGeometry/NearestNeighbors/nn_prepare.mexmaci64'
Missing symbol '_memmove' required by
'/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis->/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices-

....... more lines ........

Error in nrsearch (line 195)
            NNInfo.Atria = nn_prepare( lX );


Error in GraphDiffusion (line 261)
            [DistInfo.count, DistInfo.idxs, DistInfo.dists,DistInfo.NNInfo] = nrsearch(Points, [],
            max(G.Opts.kNN), [], lOptsTemp);


Error in run_magic (line 63)
G = GraphDiffusion(data', 0, Options);
 
Are you familiar with this issue?
Thanks, A

**Comment by dvdijk** [comment]
what version of GraphDiffusion are you using?
make sure you're using the 2014 version and not the 2016 version
so this one:
http://www.math.jhu.edu/~mauro/Code/DiffusionGeometry_01.zip

**Comment by asmagen** [comment]
Yes, I'm using this new version and it still results in the same error.

**Comment by dvdijk** [comment]
You should use the old version, not the new version

**Comment by asmagen** [comment]
I used the file that you attached.

**Comment by dvdijk** [comment]
Not sure what the cause of that error is. You can use the following code to run MAGIC without the graph diffusion package:

%% params
ka = 10; % as small as possible, try between 3 and 15
k = 30; % 3*ka
npca = 20; % try between 20 and 100
t = 6; % try between 3 and 24

%% MAGIC
[U,~,~] = randPCA(M', npca); % fast random svd
%[U,~,~] = svds(M', npca);
M_pc = M * U; % PCA project
D = squareform(pdist(M_pc)); % compute distances
knnD = sort(D); % get kNN
th = knnD(k+1,:); % find knn cutoff
ind_zero = D > repmat(th',1,size(D,2)); % kNN cutoff
sigma = knnD(ka+1,:); % locally adaptive sigma
D = bsxfun(@rdivide,D,sigma); % adapt distances
W = exp(-D.^2); % gaussian kernel
W = W + W'; % symmetrize
W(ind_zero) = 0; % kNN cutoff
L = bsxfun(@rdivide, W, sum(W,2)); % Markov normalization
L_t = L^t; % diffuse
M_new = L_t * M; % impute



M has cells on the rows and genes on the columns. M_new is the imputed data.

Let me know if this works.

**Comment by asmagen** [comment]
It works. Does this lead us to the problem?

**Comment by dvdijk** [comment]
The problem is with the external graph diffusion package (I didn't write that). My guess is that the binaries were not compiled for your platform.

**Comment by asmagen** [comment]
Are you also working on Mac OS X?

**Comment by dvdijk** [comment]
I am

**Comment by asmagen** [comment]
So is there an alternative of not using this package that makes the problem but using something like the code you provided me?

**Comment by dvdijk** [comment]
yes, thats why I pasted the code (I also pushed it see run_magic2.m) -- that code should not give you the error

**Comment by asmagen** [comment]
But I see it does randomized computation. What does it actually do?

**Comment by dvdijk** [comment]
Its just a fast PCA method
Nathan Halko, Per-Gunnar Martinsson, and Joel Tropp,
Finding structure with randomness: Stochastic algorithms
for constructing approximate matrix decompositions,
arXiv:0909.4061 [math.NA; math.PR], 2009
