### ISSUE TITLE
error loading phenograph

### ISSUE THREAD

**Issue by radio1988** [pkathail/magic#27]
Hello, 

Thanks for developing such a good tool. However I found some problem installing it on my macbook.

I used anaconda version of python. 

After running the 'pip3 install .' command, everything seems okay:

 Requirement already satisfied (use --upgrade to upgrade): magic==0.0 from file:///Users/rui/AUDREY_LAB/imputation/magic/magic in /Users/rui/anaconda/lib/python3.5/site-packages
Requirement already satisfied: numpy>=1.10.0 in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: pandas>=0.18.0 in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: scipy>=0.14.0 in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: matplotlib in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: seaborn in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: sklearn in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: networkx in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: fcsparser in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: statsmodels in /Users/rui/anaconda/lib/python3.5/site-packages (from magic==0.0)
Requirement already satisfied: python-dateutil>=2 in /Users/rui/anaconda/lib/python3.5/site-packages (from pandas>=0.18.0->magic==0.0)
Requirement already satisfied: pytz>=2011k in /Users/rui/anaconda/lib/python3.5/site-packages (from pandas>=0.18.0->magic==0.0)
Requirement already satisfied: cycler in /Users/rui/anaconda/lib/python3.5/site-packages (from matplotlib->magic==0.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,>=1.5.6 in /Users/rui/anaconda/lib/python3.5/site-packages (from matplotlib->magic==0.0)
Requirement already satisfied: scikit-learn in /Users/rui/anaconda/lib/python3.5/site-packages (from sklearn->magic==0.0)
Requirement already satisfied: decorator>=3.4.0 in /Users/rui/anaconda/lib/python3.5/site-packages (from networkx->magic==0.0)
Requirement already satisfied: setuptools in /Users/rui/anaconda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from fcsparser->magic==0.0)
Requirement already satisfied: six>=1.5 in /Users/rui/anaconda/lib/python3.5/site-packages (from python-dateutil>=2->pandas>=0.18.0->magic==0.0)

**But when I run magic_gui.py, I got and error. Here is the error message:**

magic_gui.py
Traceback (most recent call last):
  File "/Users/rui/anaconda/bin/magic_gui.py", line 12, in <module>
    import magic
  File "/Users/rui/anaconda/lib/python3.5/site-packages/magic/__init__.py", line 2, in <module>
    from . import mg
  File "/Users/rui/anaconda/lib/python3.5/site-packages/magic/mg.py", line 42, in <module>
    import phenograph
ImportError: No module named 'phenograph'

I thought this may be an issue of intalling 'phenograph', so I did: 'pip3 install phenograph' 

But I got the following error message: 
'Collecting phenograph
  Could not find a version that satisfies the requirement phenograph (from versions: )
No matching distribution found for phenograph'

Any suggestions? Thanks!

**Comment by pkathail** [comment]
How recently did you download the repository? I've removed phenograph as a dependency, so I would suggest trying to pull from the master branch and reinstalling:
git pull origin master
sudo -H pip3 uninstall magic
sudo -H pip3 install .

**Comment by radio1988** [comment]
Thank you so much! I moved to a Ubuntu machine, downloaded the newest version, uninstalled the old version, used virualenv for python environment, and 'pip3 install .' . And it now works!
