### ISSUE TITLE
Output csv files from MAGIC?

### ISSUE THREAD

**Issue by Enoxx** [pkathail/magic#35]
Hello, I am really interested in the way how MAGIC could impute gene expression in order to fill in the abundant drop-out events in single-cell RNA-Seq, and I think it would be very helpful in my case. I am using MAGIC with python and I attempted to load in a csv file onto MAGIC, and my aim would be to get an output file perhaps also in the format of csv after applying the normalisation method of MAGIC. I've tried to do this using the command lines or the user-friendly python GUI, thanks a lot for developing this tool by the way! I noticed that the output could be saved as a pickle file, but is there a way to make a csv or any text format? Thank you.

**Comment by pkathail** [comment]
If using from the command line, you can save the imputed version of the data to a csv with `data_name.magic.data.to_csv('file_name.csv')`

At the moment, the imputed data can't be saved to a csv from the GUI but it's something we will work on adding soon!

**Comment by Enoxx** [comment]
Thank you so much for the reply, I think this would be really helpful for me. At the meantime while I was trying out the command lines, I think I've got into another issue. I tried to install MAGIC in its own directory with the following command lines (python 3.3.3):
cd $HOME/magic
export PYTHONUSERBASE= $HOME/magic
pip install --user .
export PATH= $HOME/magic/bin:$PATH
export PYTHONPATH= $HOME/magic/lib64/python3.3/site-packages:$PYTHONPATH

However, I always get the same ImportError:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$HOME/magic/lib64/python3.3/site-packages/magic/__init__.py", line 1, in <module>
    from . import MAGIC
  File "$HOME/magic/lib64/python3.3/site-packages/magic/MAGIC.py", line 5, in <module>
    from sklearn.manifold.t_sne import _joint_probabilities, _joint_probabilities_nn
ImportError: cannot import name _joint_probabilities_nn

I've also tried to reinstall 'sklearn' in the directory $HOME/magic/lib64/python3.3/site-packages, unfortunately the problem remained. Could you give me some suggestions on this please? Thank you.

**Comment by pkathail** [comment]
What version of sklearn do you have installed? Note sure if this is the problem, but you could try to update to a new version by doing `pip install --upgrade sklearn`

**Comment by Enoxx** [comment]
I've tried 'pip install -U sklearn', as well as to be consistent with the version in the original package 'pip install sklearn==0.0 --user', but unfortunately still didn't make any changes.

Indeed, I too doubt that it could be an issue arisen from 'sklearn', but I couldn't manage to troubleshoot this. Thank you.

**Comment by pkathail** [comment]
Sorry, I think you should specify scikit-learn rather than sklearn. So it would be `pip install --upgrade scikit-learn`. If that doesn't work, you may want to try uninstalling & reinstalling scikit-learn (although it seems like you may have already done that), as well as scipy/numpy. It seems other people have encountered this issue as well and have been able to fix it that way (https://github.com/scikit-learn/scikit-learn/issues/3537).

**Comment by Enoxx** [comment]
Thank you for your replies! I have already tried reinstalling scikit-learn, but nothing has changed. I think maybe there are something wrong with my PYTHONPATH where the packages were loaded. I will keep you updated once if I've figured out the solution in my case. Again thank you for your help and patience.
