### ISSUE TITLE
Issues with MAGIC GUI

### ISSUE THREAD

**Issue by Thralni** [pkathail/magic#45]
Hi,

I've been trying to run MAGIC to analyze some single cell RNA seq data, but I'm running up against a number of issues that makes it hard to use the program. I installed MAGIC on my Mac which runs OS 10.12.5. 

Here is one error pertaining to loading a saved session:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/magic_gui.py", line 412, in processData
    scdata = magic.mg.SCData.load(os.path.expanduser(self.dataFileName))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/magic/mg.py", line 140, in load
    scdata = cls(data['_data'], data['_metadata'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/magic/mg.py", line 96, in __init__
    if not data_type in ['sc-seq', 'masscyt']:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/generic.py", line 955, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

I believe I have Python 3.6. When I type 'Python' in Terminal the Python version that is returned is 2.7, however, so frankly I'm not sure if it's the right one that I'm using. Any help would be appreciated.

**Comment by pkathail** [comment]
Really sorry about the delayed response! There was a bug in loading a saved session, but I believe it should be fixed in the most recent commit. If you're still having problems with it, please let me know.

**Comment by klprint** [comment]
Hi!
I get the same error with my data-set, which was freshly read in. I did only import the CSV, got the QC plots and then I wanted to plot the tSNE, but I also get the following error:

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

The same happens when I try to run the example jupyter-notebook.

**Comment by pkathail** [comment]
Hi, I was able to reproduce the error and just pushed a commit that should fix it. Please let me know if everything now works as expected.

**Comment by Thralni** [comment]
Sorry that it took em a while to get back to you. I just ran a quick test with the latest commit, and so far everything seems to work well! I'll keep chugging along and let you know if I bump into anything else.
