### ISSUE TITLE
Discrepancy between the MAGIC paper and Matlab code

### ISSUE THREAD

**Issue by NikTuzov** [pkathail/magic#46]
Hello Pooja:

Could you possibly answer the following question. In the paper a Gaussian kernel is used and it is recommended to set ka = 1/3 * k, apparently so that the corresponding sigma results in 1/3 of the nearest neighbors having substantial weight. Suppose we take a fixed pair of points,  i and j. For simplicity, assume that after knn search is performed we get that i and j are mutual neighbors, Euclidean distances Dij = Dji = D and also sigma_ij = sigmaji = sigma.

After these lines

disp 'Computing distances'
[idx, dist] = knnsearch(data_pc, data_pc, 'k', k);

disp 'Adapting sigma'
dist = bsxfun(@rdivide, dist, dist(:,ka));

the adusted distance is D/sigma. Note that D is not the squared Euclidean distance because knnsearch() does take the square root.

After this line:

disp 'Symmetrize distances'
W = W + W';

the (i,j) and (j,i) elements in W are equal to 2D/sigma. Then you compute the kernel here:

if epsilon > 0
    disp 'Computing kernel'
    [i,j,s] = find(W);
    i = [i; (1:N)'];
    j = [j; (1:N)'];
    s = [s./(epsilon^2); zeros(N,1)];
    s = exp(-s);
    W = sparse(i,j,s);
end

and the corresponding elements are set to exp(-2D/sigma). Apparently that's not a Gaussian kernel, because D is never squared (instead, epsilon is squared, but it's 1 by default). According to the paper, we should have ended up with  exp{-(D^2) / (2 * sigma^2)}. Could you please clarify the discrepancy?

Regards,
Nik

**Comment by NikTuzov** [comment]
I also looked at the Python code and it has the same issue. Unless knn search in Python returns squared distances, there is no way the kernel is Gaussian.

**Comment by dvdijk** [comment]
Hi Nik,
Thanks for pointing this out. You're right, we're actually using an exponential kernel. If you want to use a Gaussian kernel you can square the distances. It won't matter much though since we only consider the k nearest neighbors.
We will add an option to use the Gaussian kernel and we will have a new version of the manuscript up shortly.
David

**Comment by NikTuzov** [comment]
Thank you for replying. For k nearest neighbors it makes a difference in the sense that for the double exponential of the form f(x) = 1/(2*b)  * exp(-|x/b|) with b = sigma/2, the probability mass between (-sigma) and sigma is (1 - exp(-2)) ~ 0.86. For Normal kernel, the mass between plus and minus sigma is ~0.68. However, that can be adjusted by increasing k anyway. I assume the results reported in the present version of the paper use the double exponential, and so are the recommended values of k and t. 

Incidentally, have you tested MAGIC versus a solution that takes the dropouts into account explicitly, such as ZIFA or CIDR?

**Comment by dvdijk** [comment]
We haven't tested against ZIFA or CIDR. ZIFA is dimensionality reduction
and one would have to adapt it for imputation. I guess that could be done
