### ISSUE TITLE
Gene name error in the tutorial 

### ISSUE THREAD

**Issue by YubinXie** [pkathail/magic#51]
In the tutorial (http://nbviewer.jupyter.org/github/pkathail/magic/blob/develop/notebooks/Magic_single_cell_RNAseq.ipynb), it says:

2D scatter plot after MAGIC:
In [6]:``` fig, ax = scdata.magic.scatter_gene_expression(['VIM', 'CDH1'], color ='ZEB1')```

However, the gene name after MAGIC is like: "MAGIC VIM"," MAGIC CDH1". So when I ran the above codes it showed "no such genes". It will be great if you can correct this in the tutorial.

**Comment by pkathail** [comment]
Thanks for pointing this out, will update the tutorial!

**Comment by pkathail** [comment]
Fixed
