### ISSUE TITLE
Running the python implementation in R

### ISSUE THREAD

**Issue by asmagen** [pkathail/magic#54]
Hello,

Would it be possible to write a tutorial or script showing how to use this python implementation in R?

Thanks,
Assaf

**Comment by pkathail** [comment]
Sure, will look into adding that soon!

**Comment by pkathail** [comment]
Not sure if this is what you're looking for, but each of the python command line scripts can be run in R with a `system()` call. So after install MAGIC in python, you can invoke the gui by the following command in R:
`system('magic_gui.py')`

And you can run MAGIC on a csv file with this command in R:
`system('MAGIC.py -d path/to/data.csv -o path/to/output.csv')`
This will output a csv file which you can then load into R for any subsequent analysis. When calling MAGIC.py, there are also a number of other parameters you can specify, detailed in the [readme](https://github.com/pkathail/magic/blob/develop/README.md).

**Comment by pkathail** [comment]
We've added an R version of MAGIC! Instructions for installation and usage are in the README.
