### ISSUE TITLE
'~/Documents/Sophomore/Lab/wishbone/data/sdata_nn_TGFb_day_8_10.csv'

### ISSUE THREAD

**Issue by Puriney** [pkathail/magic#56]
Hi,
I was wondering where I can find the data listed in the jupyter notebook at <kbd>notebooks</kbd> (https://github.com/pkathail/magic/blob/63fa1feaa47c02a753de2df0432cd7b1cdb46d0e/notebooks/Magic_single_cell_RNAseq.ipynb).
Thanks,
Yun

**Comment by dvdijk** [comment]
Hi Yun,

We haven't made that data publicly available yet. We will in the near
future.

David

**Comment by Puriney** [comment]
Thanks for the prompt reply.
(Close the issue)

**Comment by lucapinello** [comment]
Hi @dvdijk , any update on the data availability?

Thanks!

Luca
