### ISSUE TITLE
optional deps for Python package

### ISSUE THREAD

**Issue by iosonofabio** [pkathail/magic#63]
Hi and thanks for your awesome work!

I'm including MAGIC into a larger RNA-Seq pipeline and I'm wondering whether any of the Python MAGIC dependencies could be made optional, e.g.:

1. I/O stuff (`fcsparser`, `tables`)
2. plotting stuff (e.g. `seaborn`)
3. statistics stuff (`statmodels`)

In particular, the I/O deps are used only in `mg.py` for parsers that maybe could made optional? For instance, the FCS parsing method has line [328](https://github.com/pkathail/magic/blob/develop/src/magic/mg.py#L328):

```python
metadata_channels=['Time', 'Event_length', 'DNA1', 'DNA2', 'Cisplatin', 'beadDist', 'bead1']):
```

which is probably irrelevant for most users, yet makes `fcsparser` a hard dependency for MAGIC.

Notice that `setuptools` has a mechanism in place for optional deps, you don't need to code much:

http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

What do you think? I can submit a PR if you want, it's a three liner...

**Comment by pkathail** [comment]
Sure, happy to merge in a pull request!
