### ISSUE TITLE
Rationale for filtering based on library size

### ISSUE THREAD

**Issue by fbrundu** [pkathail/magic#66]
Dear MAGIC developers,
I am running the example notebook and I'd like to understand how to proper filter out cells based on library size. From the notebook:

> The first step in data processing for MAGIC is to determine the molecule per cell and molecule per gene cutoffs with which to filter the data.
![unknown](https://user-images.githubusercontent.com/697622/34214717-471439bc-e571-11e7-917b-d7f43b085dec.png)
> From these histograms, choose the appropriate cutoffs to filter the data.

Could you point me to some rationale on how to select the appropriate cutoffs? If I read the paper correctly, this is not defined in your original paper and I think this may be defined elsewhere but I could not find any paper about it online.

Thank you,
Francesco

**Comment by dvdijk** [comment]
Hi Francesco,
Filtering based on library size depends on your specific data and the system that generated it.
Ideally you'd see a clear separation in the library size histogram where you would keep the mode that has the largest library size. The 10x pipeline does this automatically. Often however the separation between real cells and 'junk' is not so clear in which case the library size threshold is somewhat arbitrary.
Hope this is helpful
David

**Comment by fbrundu** [comment]
Thank you David.
So the assumption here is to consider junk everything that's outside of the largest mode (on the left tail). Do you know of any article which discusses it more extensively?

**Comment by dvdijk** [comment]
you could look at the 10x technology publication, they might discuss cell
filtering
https://www.nature.com/articles/ncomms14049

**Comment by fbrundu** [comment]
Dear @dvdijk,
I close this issue pointing to my [q/a on stackexchange](https://bioinformatics.stackexchange.com/a/3171/1771). It does not include comments on doublets since I didn't find a definitive method to avoid them.

Thanks,
Francesco
